/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gobee_OpenGLRenderer */

#ifndef _Included_com_gobee_OpenGLRenderer
#define _Included_com_gobee_OpenGLRenderer
#ifdef __cplusplus
extern "C"
  {
#endif

/*
 * Class:     com_xw_OpenGLRenderer
 * Method:    draw_native_scene
 * Signature: ([III)V
 */
JNIEXPORT void
JNICALL
Java_com_xw_OpenGLRenderer_draw_1native_1scene(JNIEnv *, jobject, jintArray,
    jint, jint);

/*
 * Class:     com_xw_OpenGLRenderer
 * Method:    on_surface
 * Signature: ()V
 */
JNIEXPORT void
JNICALL
Java_com_xw_OpenGLRenderer_on_1surface(JNIEnv *, jobject);

/*
 * Class:     com_xw_OpenGLRenderer
 * Method:    on_surface_changed
 * Signature: (II)V
 */
JNIEXPORT void
JNICALL
Java_com_xw_OpenGLRenderer_on_1surface_1changed(JNIEnv *, jobject, jint, jint);

#undef com_xw_xbus_XBus_MIN_PRIORITY
#define com_xw_xbus_XBus_MIN_PRIORITY 1L
#undef com_xw_xbus_XBus_NORM_PRIORITY
#define com_xw_xbus_XBus_NORM_PRIORITY 5L
#undef com_xw_xbus_XBus_MAX_PRIORITY
#define com_xw_xbus_XBus_MAX_PRIORITY 10L
/*
 * Class:     com_xw_xbus_XBus
 * Method:    xw_connect
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT jlong
JNICALL
Java_com_xw_xbus_XBus_xw_1init(JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_xw_xbus_XBus
 * Method:    xw_connect
 * Signature: (J)J
 */
JNIEXPORT void
JNICALL
Java_com_xw_xbus_XBus_xw_1connect
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_xw_xbus_XBus
 * Method:    xw_get_roster
 * Signature: ()V
 */
JNIEXPORT void
JNICALL
Java_com_xw_xbus_XBus_xw_1get_1roster(JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
