/* #undef HAVE_CLOCK_GETTIME */
/* #undef HAVE_CLOCK_SYSCALL */
/* #undef HAVE_DLFCN_H */
/* #undef HAVE_EPOLL_CTL */
/* #undef HAVE_EVENTFD */
/* #undef HAVE_FLOOR */
/* #undef HAVE_INOTIFY_INIT */
/* #undef HAVE_INTTYPES_H */
/* #undef HAVE_KQUEUE */
/* #undef HAVE_LIBRT */
/* #undef HAVE_MEMORY_H */
/* #undef HAVE_NANOSLEEP */
/* #undef HAVE_POLL */
/* #undef HAVE_POLL_H */
/* #undef HAVE_PORT_CREATE */
/* #undef HAVE_PORT_H */
/* #undef HAVE_SELECT */
/* #undef HAVE_SIGNALFD */
/* #undef HAVE_STDINT_H */
/* #undef HAVE_STDLIB_H */
/* #undef HAVE_STRINGS_H */
/* #undef HAVE_STRING_H */
/* #undef HAVE_SYS_EPOLL_H */
/* #undef HAVE_SYS_EVENTFD_H */
/* #undef HAVE_SYS_EVENT_H */
/* #undef HAVE_SYS_INOTIFY_H */
/* #undef HAVE_SYS_SELECT_H */
/* #undef HAVE_SYS_SIGNALFD_H */
/* #undef HAVE_SYS_STAT_H */
/* #undef HAVE_SYS_TYPES_H */
/* #undef HAVE_UNISTD_H */
/* #undef LT_OBJDIR */
/* #undef PACKAGE */
/* #undef PACKAGE_BUGREPORT */
/* #undef PACKAGE_NAME */
/* #undef PACKAGE_STRING */
/* #undef PACKAGE_TARNAME */
/* #undef PACKAGE_URL */
/* #undef PACKAGE_VERSION */
/* #undef VERSION */
