obj-t += $(test_dir)/parser_test1.o
obj-t += $(test_dir)/ssltest.o

test_parser-objs := $(test_dir)/parser_test1.o 
test_parser-objs += $(test_dir)/testframework.o 
#test_ssl-objs := $(test_dir)/ssltest.o 

TESTS += test_parser
#TESTS += test_ssl
